---
tags: []
layout: input_bottom
editor: code
type: interactive
extra_visible: false
manual_evaluation: false
choices: []
goal:
  kind: query_passes
  query: cd /home/mumuki/curriculum && git status
name: Creando un repositorio
